name: Prettier

# This action works with pull requests and pushes
on:
  pull_request:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Prettier
      - uses: actions/checkout@v2
      - uses: actionsx/prettier@v2
        with:
          prettier_options: -w .
